//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Average.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Average.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project is licensed under.
        /// </summary>
        internal static string Application_License_Description {
            get {
                return ResourceManager.GetString("Application.License.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apache 2.0.
        /// </summary>
        internal static string Application_License_Name {
            get {
                return ResourceManager.GetString("Application.License.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of a set of numbers divided by the number of numbers provided.
        /// </summary>
        internal static string Command_ArithmeticMean_About {
            get {
                return ResourceManager.GetString("Command.ArithmeticMean.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate the arithmetic mean of a set of numbers.
        /// </summary>
        internal static string Command_ArithmeticMean_Description {
            get {
                return ResourceManager.GetString("Command.ArithmeticMean.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Command_GeometricMean_About {
            get {
                return ResourceManager.GetString("Command.GeometricMean.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate the geometric mean of a set of numbers.
        /// </summary>
        internal static string Command_GeometricMean_Description {
            get {
                return ResourceManager.GetString("Command.GeometricMean.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the truncated mean of the interquartile range of a set of values..
        /// </summary>
        internal static string Command_InterquartileMean_Description {
            get {
                return ResourceManager.GetString("Command.InterquartileMean.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints the License to the Terminal output..
        /// </summary>
        internal static string Command_License_Description {
            get {
                return ResourceManager.GetString("Command.License.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the middle value in a set of numbers..
        /// </summary>
        internal static string Command_Median_Description {
            get {
                return ResourceManager.GetString("Command.Median.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the arithmetic mean of the smallest and largest values in an array..
        /// </summary>
        internal static string Command_MidRange_Description {
            get {
                return ResourceManager.GetString("Command.MidRange.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the most common value(s) found within a set of numbers..
        /// </summary>
        internal static string Command_Mode_Description {
            get {
                return ResourceManager.GetString("Command.Mode.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error(s).
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid number of inputs was provided. At least X values were required..
        /// </summary>
        internal static string Errors_InvalidInputCount {
            get {
                return ResourceManager.GetString("Errors.InvalidInputCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Input Provided.
        /// </summary>
        internal static string Errors_NoInput_Title {
            get {
                return ResourceManager.GetString("Errors.NoInput.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The results file couldn&apos;t be saved. Here&apos;s why:.
        /// </summary>
        internal static string File_Save_Error {
            get {
                return ResourceManager.GetString("File.Save.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The results file was successfully saved to.
        /// </summary>
        internal static string File_Save_Success {
            get {
                return ResourceManager.GetString("File.Save.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The numbers to get the average of.
        /// </summary>
        internal static string Numbers_Description {
            get {
                return ResourceManager.GetString("Numbers.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the results with prettier formatting..
        /// </summary>
        internal static string Output_Pretty_Description {
            get {
                return ResourceManager.GetString("Output.Pretty.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the results without pretty formatting..
        /// </summary>
        internal static string Output_Standard_Description {
            get {
                return ResourceManager.GetString("Output.Standard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of decimal places to round the result to.
        /// </summary>
        internal static string Rounding_DecimalPlaces_Description {
            get {
                return ResourceManager.GetString("Rounding.DecimalPlaces.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of significant figures to round the result to.
        /// </summary>
        internal static string Rounding_SignificantFigures_Description {
            get {
                return ResourceManager.GetString("Rounding.SignificantFigures.Description", resourceCulture);
            }
        }
    }
}
