//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caesar.localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Caesar.localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode text using the Caesar Cipher, either using a number provided or a random number..
        /// </summary>
        internal static string Command_Decode_Label {
            get {
                return ResourceManager.GetString("Command.Decode.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode text using the Caesar Cipher, either using a number provided or a random number..
        /// </summary>
        internal static string Command_Encode_Label {
            get {
                return ResourceManager.GetString("Command.Encode.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints the License Notice to the terminal..
        /// </summary>
        internal static string Command_License {
            get {
                return ResourceManager.GetString("Command.License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to provide the words to be encoded..
        /// </summary>
        internal static string Exception_Argument_NoWords {
            get {
                return ResourceManager.GetString("Exception.Argument.NoWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File_Path.
        /// </summary>
        internal static string FilePath_Label {
            get {
                return ResourceManager.GetString("FilePath.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text file to get words to be encoded or decoded..
        /// </summary>
        internal static string Input_Description {
            get {
                return ResourceManager.GetString("Input.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text file to save the encoded or decoded value as..
        /// </summary>
        internal static string Output_Description {
            get {
                return ResourceManager.GetString("Output.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount_To_Shift.
        /// </summary>
        internal static string Shift_Amount_Description {
            get {
                return ResourceManager.GetString("Shift.Amount.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number to shift each character by..
        /// </summary>
        internal static string Shift_Description {
            get {
                return ResourceManager.GetString("Shift.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of caesar being used..
        /// </summary>
        internal static string Version_Description {
            get {
                return ResourceManager.GetString("Version.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The words to be decoded..
        /// </summary>
        internal static string Words_Decode_Description {
            get {
                return ResourceManager.GetString("Words.Decode.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The words to be encoded..
        /// </summary>
        internal static string Words_Encode_Description {
            get {
                return ResourceManager.GetString("Words.Encode.Description", resourceCulture);
            }
        }
    }
}
