//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnviousBox.Cli.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnviousBox.Cli.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of a set of numbers divided by the number of numbers provided.
        /// </summary>
        internal static string Apps_Average_Command_ArithmeticMean_About {
            get {
                return ResourceManager.GetString("Apps.Average.Command.ArithmeticMean.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate the arithmetic mean of a set of numbers.
        /// </summary>
        internal static string Apps_Average_Command_ArithmeticMean_Description {
            get {
                return ResourceManager.GetString("Apps.Average.Command.ArithmeticMean.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate the geometric mean of a set of numbers.
        /// </summary>
        internal static string Apps_Average_Command_GeometricMean_Description {
            get {
                return ResourceManager.GetString("Apps.Average.Command.GeometricMean.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the truncated mean of the interquartile range of a set of values..
        /// </summary>
        internal static string Apps_Average_Command_InterquartileMean_Description {
            get {
                return ResourceManager.GetString("Apps.Average.Command.InterquartileMean.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the middle value in a set of numbers..
        /// </summary>
        internal static string Apps_Average_Command_Median_Description {
            get {
                return ResourceManager.GetString("Apps.Average.Command.Median.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the arithmetic mean of the smallest and largest values in an array..
        /// </summary>
        internal static string Apps_Average_Command_MidRange_Description {
            get {
                return ResourceManager.GetString("Apps.Average.Command.MidRange.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the most common value(s) found within a set of numbers..
        /// </summary>
        internal static string Apps_Average_Command_Mode_Description {
            get {
                return ResourceManager.GetString("Apps.Average.Command.Mode.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode text using the Caesar Cipher, either using a number provided or a random number..
        /// </summary>
        internal static string Apps_Caesar_Command_Decode_Label {
            get {
                return ResourceManager.GetString("Apps.Caesar.Command.Decode.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode text using the Caesar Cipher, either using a number provided or a random number..
        /// </summary>
        internal static string Apps_Caesar_Command_Encode_Label {
            get {
                return ResourceManager.GetString("Apps.Caesar.Command.Encode.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round a number to a specified number of decimal places..
        /// </summary>
        internal static string Apps_Round_Command_Round_Decimal_Description {
            get {
                return ResourceManager.GetString("Apps.Round.Command.Round.Decimal.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round a number to a specified number of Significant Figures..
        /// </summary>
        internal static string Apps_Round_Command_Round_SignificantFigure_Description {
            get {
                return ResourceManager.GetString("Apps.Round.Command.Round.SignificantFigure.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round a given number to a specified number of decimal places or significant figures.
        ///.
        /// </summary>
        internal static string Apps_Round_Description {
            get {
                return ResourceManager.GetString("Apps.Round.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No number to be rounded was provided..
        /// </summary>
        internal static string Apps_Round_Error_Number_NoInput {
            get {
                return ResourceManager.GetString("Apps.Round.Error.Number.NoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value you provided was.
        /// </summary>
        internal static string Apps_Round_Input_ProvidedValue {
            get {
                return ResourceManager.GetString("Apps.Round.Input.ProvidedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value rounded to the precision you specified.
        /// </summary>
        internal static string Apps_Round_Input_RoundedValue {
            get {
                return ResourceManager.GetString("Apps.Round.Input.RoundedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of Decimal Places you wanted was.
        /// </summary>
        internal static string Apps_Round_Input_Rounding_DecimalPlaces {
            get {
                return ResourceManager.GetString("Apps.Round.Input.Rounding.DecimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t provide the number of Decimal Places you wanted, so we defaulted to.
        /// </summary>
        internal static string Apps_Round_Input_Rounding_DecimalPlaces_NotProvided {
            get {
                return ResourceManager.GetString("Apps.Round.Input.Rounding.DecimalPlaces.NotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of Significant Figures you wanted was.
        /// </summary>
        internal static string Apps_Round_Input_Rounding_SignificantFigures {
            get {
                return ResourceManager.GetString("Apps.Round.Input.Rounding.SignificantFigures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t provide the number of Significant Figures you wanted, so we defaulted to.
        /// </summary>
        internal static string Apps_Round_Input_Rounding_SignificantFigures_NotProvided {
            get {
                return ResourceManager.GetString("Apps.Round.Input.Rounding.SignificantFigures.NotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error(s).
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid number of inputs was provided. At least X values were required..
        /// </summary>
        internal static string Errors_InvalidInputCount {
            get {
                return ResourceManager.GetString("Errors.InvalidInputCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Input Provided.
        /// </summary>
        internal static string Errors_NoInput_Title {
            get {
                return ResourceManager.GetString("Errors.NoInput.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The results file couldn&apos;t be saved. Here&apos;s why:.
        /// </summary>
        internal static string File_Save_Error {
            get {
                return ResourceManager.GetString("File.Save.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The results file was successfully saved to..
        /// </summary>
        internal static string File_Save_Success {
            get {
                return ResourceManager.GetString("File.Save.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file specified already exists..
        /// </summary>
        internal static string File_Saved_AlreadyExists {
            get {
                return ResourceManager.GetString("File.Saved.AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The numbers to get the average of..
        /// </summary>
        internal static string Numbers_Description {
            get {
                return ResourceManager.GetString("Numbers.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the results with prettier formatting..
        /// </summary>
        internal static string Output_Pretty_Description {
            get {
                return ResourceManager.GetString("Output.Pretty.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the results without pretty formatting..
        /// </summary>
        internal static string Output_Standard_Description {
            get {
                return ResourceManager.GetString("Output.Standard.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of decimal places to round the result to..
        /// </summary>
        internal static string Rounding_DecimalPlaces_Description {
            get {
                return ResourceManager.GetString("Rounding.DecimalPlaces.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of significant figures to round the result to.
        /// </summary>
        internal static string Rounding_SignificantFigures_Description {
            get {
                return ResourceManager.GetString("Rounding.SignificantFigures.Description", resourceCulture);
            }
        }
    }
}
